### ISSUE TITLE
Adding defines / libs

### ISSUE THREAD

**Issue by quakemmo** [jpcy/ioq3-premake-msvc#2]
Thank you for your project, it works beautifully with VS19.
At least, with the 64 bit build.  The 32 bit build failed here FYI - not that this is a big deal as far as I'm concerned.

Quick question:

What I'm trying to achieve is to be able to use the VS19 debugger on my ioq3 fork - it's a full conversion and will be released soonish. To build the client, I need to meet the following criteria:

Achieved:
- Build native DLL code for the ui, cgame, renderer and qagame, no QVM

Pending:
- Link with the SDL2_ttf library
- Link with the freetype library
- Add a couple additionnal defines to the build process
- Add a bunch of .c and .h files (my code) into the cgame,  ui, etc.. projects
- I don't care if the server builds or not. I just need to debug the client.  I will be doing actual release builds with MINGW

What would be the proper workflow to achieve this all with your scripts?

I'm currently using the following command line instead of the provided vs2019.bat

premake5 --disable-server --disable-missionpack --disable-game-qvm --rename-baseq3=xq --standalone vs2019

Thanks!

**Comment by jpcy** [comment]
Just copy premake5.lua to your own project and maintain your own modified version. Even if you've never used premake before it's fairly straightforward. e.g. add defines to the ioquake3 project [here](https://github.com/jpcy/ioq3-premake-msvc/blob/master/premake5.lua#L152). Library files in ["links"](https://github.com/jpcy/ioq3-premake-msvc/blob/master/premake5.lua#L220) can be a relative or absolute path to a externally built .lib file. cgame/game/ui files are [here](https://github.com/jpcy/ioq3-premake-msvc/blob/master/premake5.lua#L538).

**Comment by quakemmo** [comment]
Thanks. I will try that.

**Comment by quakemmo** [comment]
I installed LUA53, and am trying to run premake5.lua (instead of premake5.exe).
I have NOT modified premake5.lua in any way (yet).


I get the error:

C:\dev\xqc>lua53 premake5.lua --disable-server --disable-missionpack --disable-game-qvm --rename-baseq3=xq --standalone vs2019
lua53: premake5.lua:1: attempt to call a nil value (global 'newoption')
stack traceback:
        premake5.lua:1: in main chunk
        [C]: in ?

**Comment by jpcy** [comment]
Premake needs to host the script - it won't work with plain lua.
